sudo: false
language: rust

rust:
  - stable
  - nightly

os:
  - linux

env:
  - ARCH=i686 RUST_BACKTRACE=1
  - ARCH=x86_64 RUST_BACKTRACE=1

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

notifications:
  email: false