[package]
name = "pagoda_bot"
version = "0.1.0"
authors = ["Matheus Macabu <mkbu95@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8.4"
telegram-bot = "0.6"
futures = "0.1.17"
tokio-core = "0.1.12"
dotenv = "0.10.1"